Aggiunta sezione Analisi dei Rischi
lineCode-swe/docs pull request #46
Opened 2020-12-29 15:02 UTC by Shwny

Non è incluso il rischio di indisponibilità delle piattaforme di comunicazione. Viene inglobato nel rischio "Strumenti Software". Controllare sintassi degli elenchi puntati.

2021-01-02 16:03 UTC, essepi78 approved these changes

2021-01-02 16:34 UTC, essepi78 requested changes

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +			\item Conseguenze che il manifestarsi del rischio potrebbe avere.
iniziale minuscola

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +				\item Stabilire le modalità attraverso cui reagire al verificarsi di un rischio.
iniziale minuscola

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +				\item Piano di contingenza.
iniziale minuscola

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item Rischi legati ai mezzi tecnologici
iniziale minuscola e punteggiatura finale

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item \textbf{Controllo}: il Responsabile aiuterà i membri che incontrano difficoltà attraverso delle attività di auto-miglioramento.
; finale

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item \textbf{Controllo}: il Responsabile andrà a moderare gli incontri tra i membri e avrà l'onere di assicurare un ambiente di lavoro sano per tutti.
; finale

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item \textbf{Piano di contingenza}: il Responsabile provvederà a coordinare il gruppo per redistribuire il lavoro in eccesso e moderare la nuova pianificazione dei lavori;
. finale

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item \textbf{Controllo}: l'analisi dei requisiti verrà periodicamente rivista e controllata in fase di redazione al fine di migliorarla e raffinarla continuativamente.
; finale

2021-01-02 16:34 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item \textbf{Controllo}: ciascun membro cerca, per quanto possibile, di avere cura della propria attrezzatura.
; finale

2021-01-04 16:01 UTC, Shwny commented
Ho ricontrollato e modificato quanto richiesto per rendere il documento conforme allo standard dichiarato nelle norme. Richiedo verifica urgente per effettuare ulteriori modifiche.

2021-01-04 16:04 UTC, Shwny commented
Inoltre, le modifiche richieste rispetto ai ";" e "." ancora non mi sono chiare: il "." deve essere inserito al termine di un singolo elenco puntato o alla fine di una sequenza, anche separata, di elenchi?

2021-01-04 16:08 UTC, essepi78 requested changes

2021-01-04 16:08 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +			\item pattore di rischio;
fattore

2021-01-04 16:08 UTC, essepi78 commented on esterni/piano_progetto/res/sez2_analisi_rischi.tex
> +		\item rischi legati ai mezzi tecnologici
mancano i 3 ; e il punto all'ultima voce

2021-01-04 16:10 UTC, essepi78 commented
> Inoltre, le modifiche richieste rispetto ai ";" e "." ancora non mi sono chiare: il "." deve essere inserito al termine di un singolo elenco puntato o alla fine di una sequenza, anche separata, di elenchi?

ogni singola voce dell'elenco termina con ; tranne l'ultima (voce dell'elenco) che termina con il .

2021-01-04 16:18 UTC, essepi78 approved these changes

2021-01-04 16:45 UTC, merged